version: '3'
services:
  node:
    environment:
      - PROJECT_DIR=react_sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./code:/code
    command: ./start.sh
    ports:
     - "8080:8080"
    tty: true
